### ISSUE TITLE
Android RAM req?

### ISSUE THREAD

**Issue by ClashSAN** [freedomtan/keras_cv_stable_diffusion_to_tflite#2]
Hi! running the quantized models on android sounds pretty exciting. were you able to run inference with a 4gb device? It is also interesting to know what kind of processor you had used! thanks!

**Comment by freedomtan** [comment]
> Hi! running the quantized models on android sounds pretty exciting. were you able to run inference with a 4gb device? It is also interesting to know what kind of processor you had used! thanks!

never tried on devices with 4 GiB or less. I work for a SoC company, we have all kinds of fancy Android devices with large amount of DRAM. Mainly on devices with [MediaTek 9000/9000+/9200 series](https://www.mediatek.com/products/smartphones/dimensity-5g)

**Comment by ClashSAN** [comment]
thank you for your reply, I hope to learn more by experiment!
